### PR TITLE
 API Move search and Solr classes into cwp-search module

### PR DESCRIPTION
**Pull request by robbieaverill**
This pull request moves the search/Solr related code from the cwp/cwp and cwp/cwp-core modules into this module, as well as:

* Migrate translations from cwp/cwp related to search
* Sets new namespaces, with upgrader mapping file
* New Transifex config added (set up in Transifex with these pushed to it)
* Search logic from BasePageController in cwp/cwp moved to a new extension in this module
* Search boosting and synonyms tested

## Requirements

The following PRs are required for the builds to pass here (they're passing locally):

- [x] https://github.com/silverstripe/cwp-core/pull/15
- [x] https://github.com/silverstripe/cwp/pull/30

### CODE REVIEW

**Review by NightJar — APPROVED** [review]
I approve of this work :D

**Comment by NightJar** [comment]
Travis is unhappy though. So unhappy it doesn't even want to tell me what it's unhappy about. May just be a service issue. Otherwise I'd assume it's the prerequsite `cwp/cwp-core` and `cwp/cwp` related PRs being merged. I've restarted the build so we'll see what happens.

**Comment by robbieaverill** [comment]
There's two requirements listed in the ticket description - the tests should pass once they're both merged

**Comment by NightJar** [comment]
Yeah, it's just odd it doesn't want to show me the logs. In any case they're both merged and I've re-restarted the job.

**Comment by robbieaverill** [comment]
I've tagged a new beta for fulltextsearch to fix the original error of the missing test state

**Pull request merged**
