### PR TITLE
Make spellcheck configurable

### PR DESCRIPTION
**Pull request by wilr**

### CODE REVIEW

**Review by robbieaverill — APPROVED** [review]

**Comment by emteknetnz** [comment]
@wilr could you retarget/rebase this to the `1` branch instead of `master`

**Comment by wilr** [comment]
@emteknetnz done.

**Comment by emteknetnz** [comment]
Restarting travis.  When that's green I'll look to give this a quick test and merge

**Comment by emteknetnz** [comment]
@wilr travis is still trying to build this against the master branch - https://travis-ci.org/github/silverstripe/cwp-search/builds/601068458

I think you may need to rebase this on top of `1` and force push it to get it to build against `1`

**Pull request merged**
